/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package w1679752.fyp.imagesteganography;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author hamida
 */
public class MenuFrame extends javax.swing.JFrame {

    /**
     * Creates new form MenuFrame
     */
    public MenuFrame() {

        initComponents();
        //Centers The Frame 
        setLocationRelativeTo(null);
        //Puts A Background Image On The Menu Frame
        try {
            BufferedImage backgroundImage = null;

            //Load The Image From The File Path
            File selectedImage = new File("BGroundImage.jpeg");
            backgroundImage = ImageIO.read(selectedImage);

            //An Image Icon Is Created With The Cover Image
            ImageIcon labelIcon = new ImageIcon(backgroundImage);

            //Scales The Image To The Same Size As The JLabel It Will Be Displayed In 
            Image scaleImage = labelIcon.getImage().getScaledInstance(ImageLabel.getWidth(), ImageLabel.getHeight(), Image.SCALE_SMOOTH);

            //The Scaled Icon
            ImageIcon backgroundIcon = new ImageIcon(scaleImage);

            //Displays The Image In The JLabel
            ImageLabel.setIcon(backgroundIcon);
        } catch (IOException ex) {
            Logger.getLogger(MenuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EmbedImageBtn = new javax.swing.JButton();
        ExtractTextBtn = new javax.swing.JButton();
        CloseBtn = new javax.swing.JButton();
        TitleLabel = new javax.swing.JLabel();
        ImageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Image Steganography Tool");
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        EmbedImageBtn.setFont(new java.awt.Font("Lucida Grande", 3, 16)); // NOI18N
        EmbedImageBtn.setForeground(new java.awt.Color(13, 44, 65));
        EmbedImageBtn.setText("Embed Image");
        EmbedImageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmbedImageBtnActionPerformed(evt);
            }
        });
        getContentPane().add(EmbedImageBtn);
        EmbedImageBtn.setBounds(170, 170, 140, 50);

        ExtractTextBtn.setFont(new java.awt.Font("Lucida Grande", 3, 16)); // NOI18N
        ExtractTextBtn.setForeground(new java.awt.Color(13, 44, 65));
        ExtractTextBtn.setText("Extract Text");
        ExtractTextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExtractTextBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ExtractTextBtn);
        ExtractTextBtn.setBounds(170, 230, 140, 50);

        CloseBtn.setFont(new java.awt.Font("Lucida Grande", 3, 16)); // NOI18N
        CloseBtn.setForeground(new java.awt.Color(13, 44, 65));
        CloseBtn.setText("Close");
        CloseBtn.setActionCommand("Everything");
        CloseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBtnActionPerformed(evt);
            }
        });
        getContentPane().add(CloseBtn);
        CloseBtn.setBounds(170, 290, 140, 50);

        TitleLabel.setFont(new java.awt.Font("Lucida Grande", 1, 26)); // NOI18N
        TitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        TitleLabel.setText("Image Steganography Tool");
        getContentPane().add(TitleLabel);
        TitleLabel.setBounds(70, 20, 360, 50);

        ImageLabel.setText("ImageLabel");
        getContentPane().add(ImageLabel);
        ImageLabel.setBounds(0, 0, 500, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Opens The Embed Cover Image With Text Frame
    private void EmbedImageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmbedImageBtnActionPerformed
        // TODO add your handling code here:
        new EmbedImageFrame().setVisible(true);
    }//GEN-LAST:event_EmbedImageBtnActionPerformed
    //Opens The Extract Text From The Carrier Image Frame
    private void ExtractTextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExtractTextBtnActionPerformed
        // TODO add your handling code here:
        new ExtractTextFrame().setVisible(true);
    }//GEN-LAST:event_ExtractTextBtnActionPerformed
    //Exits The System
    private void CloseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBtnActionPerformed
        // TODO add your handling code here:
        //setVisible(false);
        System.exit(0);


    }//GEN-LAST:event_CloseBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseBtn;
    private javax.swing.JButton EmbedImageBtn;
    private javax.swing.JButton ExtractTextBtn;
    private javax.swing.JLabel ImageLabel;
    private javax.swing.JLabel TitleLabel;
    // End of variables declaration//GEN-END:variables
}
